import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
import { decode_jwt } from "@/api/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Car Spotters Anonymous",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [username, setUsername] = useState('');

  useEffect(() => {
    const encodedUsername = localStorage.getItem('token');

    if (!encodedUsername) {
      window.location.href = '/login';
    }
    
    const decode = async () => {
      const decoded = await decode_jwt(encodedUsername as string);
      setUsername(decoded as string);
    };

    decode();
  }, []);

  return (
    <html lang="en" className="bg-black">
      <body className="">{children}</body>
    </html>
  );
}
